# Change these first
owner: Nau-media-AG
repo: uptime

sites:
  - name: Nau
    url: https://www.nau.ch
  - name: API Ping
    url: https://api.nau.ch/monitoring/ping
  - name: API Frontpage
    url: https://api.nau.ch/v3/frontpage
  - name: Nau Health
    url: https://health.nau.ch
  - name: Nau Living
    url: https://living.nau.ch
  - name: Nau Liebe
    url: https://liebe.nau.ch
  - name: Nau Luxury
    url: https://luxury.nau.ch
  - name: Nau Family
    url: https://family.nau.ch
  - name: Nau Food
    url: https://food.nau.ch
  - name: Nau Tiere
    url: https://tiere.nau.ch
  - name: Nau Travel
    url: https://travel.nau.ch
  - name: Nau Automobile
    url: https://automobile.nau.ch
  - name: Nau Techtrends
    url: https://techtrends.nau.ch
  - name: Nau Beauty
    url: https://beauty.nau.ch
  - name: Analytics
    url: https://t.nau.ch
  - name: Nau Media AG
    url: https://nau-media.ch
  - name: Nau Bern
    url: https://bern.nau.ch
  - name: Nau Luzern
    url: https://luzern.nau.ch
  - name: Nau Zürich
    url: https://zurich.nau.ch
  - name: Nau Basel
    url: https://basel.nau.ch
  - name: Nau Aargau
    url: https://aargau.nau.ch
  - name: Nau Ost
    url: https://ost.nau.ch
  - name: Nau Bern API
    url: https://api.nau.ch/region-pages/pages?region=bern&path=/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Nau Media AG** Status Monitoring"
  introMessage: "Here, you can find real-time information about the operational status of our services, including our news platform and digital media content. We are committed to providing continuous access to our news coverage, and this page is your source for updates on any service interruptions or maintenance activities. Stay informed about the uptime and performance of Nau Media AG's digital offerings. _Please note that response times are measured from the USA, which may affect latency and performance metrics displayed here._"
  navbar:
    - title: Status
      href: /
  robotsText: "User-agent: * \nDisallow: /"
  metaTags:
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
